/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lantern_win_WindowsProxifier */

#ifndef _Included_org_lantern_win_WindowsProxifier
#define _Included_org_lantern_win_WindowsProxifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lantern_win_WindowsProxifier
 * Method:    proxy
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lantern_win_WindowsProxifier_proxy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lantern_win_WindowsProxifier
 * Method:    unproxy
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lantern_win_WindowsProxifier_unproxy
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
