/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lantern_win_WinProxy */

#ifndef _Included_org_lantern_win_WinProxy
#define _Included_org_lantern_win_WinProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lantern_win_WinProxy
 * Method:    proxy
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lantern_win_WinProxy_proxy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lantern_win_WinProxy
 * Method:    setPacFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lantern_win_WinProxy_setPacFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lantern_win_WinProxy
 * Method:    getPacFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lantern_win_WinProxy_getPacFile
  (JNIEnv *, jobject);

/*
 * Class:     org_lantern_win_WinProxy
 * Method:    unproxy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lantern_win_WinProxy_unproxy
  (JNIEnv *, jobject);

/*
 * Class:     org_lantern_win_WinProxy
 * Method:    getProxy
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lantern_win_WinProxy_getProxy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
